create table if not exists public.source_items (
  id bigint generated by default as identity primary key,
  content text not null,
  source_type text not null default 'text',
  created_at timestamptz not null default now()
);

create table if not exists public.memories (
  id bigint generated by default as identity primary key,
  source_item_id bigint not null references public.source_items(id) on delete cascade,
  kind text not null check (kind in ('person', 'project', 'idea', 'commitment')),
  content text not null,
  confidence integer not null check (confidence >= 0 and confidence <= 100),
  rationale text not null default '',
  metadata_json jsonb,
  status text not null default 'active' check (status in ('active', 'needs_review', 'done', 'dismissed')),
  created_at timestamptz not null default now()
);

create table if not exists public.recall_feedback (
  id bigint generated by default as identity primary key,
  query text not null,
  action text not null check (action in ('not_relevant', 'promote_to_memory', 'add_context')),
  source_item_id bigint not null references public.source_items(id) on delete cascade,
  memory_id bigint references public.memories(id) on delete set null,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.research_queue_items (
  id bigint generated by default as identity primary key,
  source_item_id bigint references public.source_items(id) on delete cascade,
  memory_id bigint references public.memories(id) on delete set null,
  status text not null default 'queued' check (status in ('queued', 'done', 'dismissed')),
  created_at timestamptz not null default now(),
  check (source_item_id is not null or memory_id is not null)
);

create table if not exists public.youtube_sources (
  id bigint generated by default as identity primary key,
  source_item_id bigint not null unique references public.source_items(id) on delete cascade,
  url text not null,
  video_id text not null,
  title text,
  channel text,
  ty_note text,
  transcript_status text not null default 'unavailable' check (transcript_status in ('available', 'unavailable')),
  summary text,
  created_at timestamptz not null default now()
);

alter table public.research_queue_items enable row level security;
alter table public.youtube_sources enable row level security;

create index if not exists idx_source_items_created_at on public.source_items(created_at desc, id desc);
create index if not exists idx_memories_source_item_id on public.memories(source_item_id);
create index if not exists idx_memories_kind on public.memories(kind);
create index if not exists idx_memories_status on public.memories(status);
create index if not exists idx_recall_feedback_source_item_id on public.recall_feedback(source_item_id);
create index if not exists idx_research_queue_items_source_item_id on public.research_queue_items(source_item_id);
create index if not exists idx_research_queue_items_memory_id on public.research_queue_items(memory_id);
create index if not exists idx_youtube_sources_video_id on public.youtube_sources(video_id);
